version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_container
    ports:
      - "27017:27017"

    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - docker_data:/data/db
      # ⚠️ 可選：在初次啟動時，執行位於這個目錄下的任何 .js 腳本
      # - ./init-scripts:/docker-entrypoint-initdb.d

    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    ports:
      - "27018:8081"

    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}

      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    restart: unless-stopped

    depends_on:
      - mongodb

volumes:
  docker_data: